FROM mansong/jmbase
LABEL maintainer="Martin Ansong"

# Ports to be exposed for Jmeter Slave
EXPOSE 1099 50000

# Application to run on startup
ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
            -Dserver.rmi.localport=50000 \
            -Dserver_port=1099 \
            -Jserver.rmi.ssl.disable=true